compilerPath: /opt/cloudbear/bin/riscv64-unknown-elf-gcc
spikePath: /usr/bin/spike
gdbPath: /home/lavrinenko/project/xpack-riscv-none-elf-gcc-13.2.0-2/bin/riscv-none-elf-gdb
openocdPath: /usr/local/bin/openocd
